# Generated by Django 2.2.13 on 2020-06-14 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('action_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators_action_user', to=settings.AUTH_USER_MODEL)),
                ('user_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators_user_1', to=settings.AUTH_USER_MODEL)),
                ('user_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='collaborators',
            constraint=models.UniqueConstraint(fields=('user_id_1', 'user_id_2'), name='unique_friendship'),
        ),
    ]
